### ISSUE TITLE
商品出品ページ、イメージ取り込み部分jqueryが発火していない。

### ISSUE THREAD

**Issue by iemoto** [TAKUYA-KUSAKABE/fake_merc#53]
表題の通り

[![Screenshot from Gyazo](https://gyazo.com/f6645f2e985db74f8d2e939eee85a953/raw)](https://gyazo.com/f6645f2e985db74f8d2e939eee85a953)

**Comment by TAKUYA-KUSAKABE** [comment]
haml側のクラス名が存在していませんでした。

おそらく、マージした際に削除されたのだと思います。
PRのBug fixにて、解決済みです。

**Comment by iemoto** [comment]
了解！ありがとうございます。
